# Generated by Django 5.1.2 on 2024-11-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
