# Generated by Django 5.1.2 on 2024-11-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_checkout_email_alter_checkout_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='create_account',
        ),
    ]
