# Generated by Django 5.1.2 on 2024-11-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_product_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
