# Generated by Django 5.1.2 on 2024-11-07 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/%Y/%m/%d')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('last_price', models.PositiveIntegerField(blank=True, null=True)),
                ('add_to_cart', models.CharField(blank=True, max_length=225, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='shop.categories')),
            ],
        ),
    ]
