# Generated by Django 5.1.2 on 2024-11-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_slug_alter_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
