# Generated by Django 5.1.2 on 2024-11-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='last_price',
        ),
        migrations.AddField(
            model_name='shop',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
