# Generated by Django 5.1.2 on 2024-11-07 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_shop_last_price_shop_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['title'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shop.categories'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['slug'], name='shop_catego_slug_a1542a_idx'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['title'], name='shop_catego_title_645a67_idx'),
        ),
    ]
