# Generated by Django 5.1.2 on 2024-11-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_categories_options_alter_shop_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
