# Generated by Django 5.1.2 on 2024-11-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shop_is_new_shop_is_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
