# Generated by Django 5.1.2 on 2024-11-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_title_about_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
