# Generated by Django 5.1.2 on 2024-11-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=125, null=True)),
                ('phone', models.CharField(blank=True, max_length=125, null=True)),
                ('email', models.CharField(blank=True, max_length=125, null=True)),
                ('instagram', models.CharField(blank=True, max_length=125, null=True)),
                ('youtube', models.CharField(blank=True, max_length=125, null=True)),
                ('linkdin', models.CharField(blank=True, max_length=125, null=True)),
                ('telegram', models.CharField(blank=True, max_length=125, null=True)),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': 'infos',
            },
        ),
    ]
