# Generated by Django 5.1.2 on 2024-11-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='locations',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
