# Generated by Django 5.1.2 on 2024-11-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_info_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='locations',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
